### ISSUE TITLE
Stripping from built code

### ISSUE THREAD

**Issue by Kuzirashi** [dbazile/ember-cli-comment-defeature#2]
Hey, great addon! After this code is commented is this stripped from frontend.js? :)

**Comment by dbazile** [comment]
In development watch, the commented-out code will be emitted into the JS that gets sent to the browser.  In production builds, the commented-out code will be stripped during minification.

**Comment by Kuzirashi** [comment]
Great. Thank you for quick answer! :)

**Comment by dbazile** [comment]
Not a problem.  Happy hacking! :)
